- name: "♻️Refactor"
  color: "e4e669"
  description: "코드 구조 개선"

- name: "✨Feature"
  color: "0075ca"
  description: "새 기능 추가"

- name: "🐛Fix"
  color: "d73a4a"
  description: "버그 수정"

- name: "⚙️Chore"
  color: "ededed"
  description: "설정, 환경 변경"

- name: "🖼️Assets"
  color: "c2e0c6"
  description: "이미지, 폰트 등 에셋 추가"

- name: "🎨Style"
  color: "f9d0c4"
  description: "UI / 스타일 변경"
